exclude = [
    ".git",
    ".idea",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "site-packages",
]

line-length = 79
indent-width = 4
fix = true
preview = true

[lint]
select = ["F", "E", "W", "C90", "I", "N", "D", "UP", "ANN", "ASYNC", "S",
    "BLE", "FBT", "B", "A", "COM", "C4", "DTZ", "EM", "ISC", "ICN", "LOG",
    "G", "INP", "PIE", "T20", "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM",
    "TID", "TCH", "INT", "ARG", "PTH", "TD", "PD", "PGH", "PL", "TRY", "FLY",
    "NPY", "FAST", "PERF", "FURB", "DOC", "RUF"]
ignore = ["COM812", "ISC001"]

[lint.per-file-ignores]
"__init__.py" = ["D104"]

[lint.isort]
lines-after-imports = 2
combine-as-imports = true

[lint.pydocstyle]
convention = "numpy"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 72
