exclude = [
    ".git",
    ".idea",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "site-packages",
]

line-length = 88
indent-width = 4
fix = true
preview = true

[lint]
select = ["A", "B", "C", "D", "E", "F", "I", "N", "Q", "W", "ANN", "ARG",
    "ASYNC", "COM", "C4", "DOC", "FURB", "FLY", "ICN", "INT", "ISC", "NPY",
    "PD", "PERF", "PIE", "PL", "PT", "PTH", "RET", "RUF", "SIM", "SLF",
    "TCH", "TID", "TRY", "T20", "UP"]
ignore = ["ANN101", "COM812", "D203", "D205", "D211", "D212", "D400",
    "D401", "D415", "ISC001", "PERF203", "PLR0913"]

[lint.per-file-ignores]
"__init__.py" = ["D104", "E402", "F401", "F403", "F811"]

[lint.isort]
lines-after-imports = 2
combine-as-imports = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
